default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     25
  timeout:  5000

development:
  <<: *default
  database: gridvue_development

test:
  <<: *default
  database: gridvue_test

production:
  <<: *default
  database: gridvue_production
